### ISSUE TITLE
redflare link

### ISSUE THREAD

**Issue by bonifarz** [TheAssassin/redflare-python#1]
in REDME.md, you link to redflare as https://redflare.ofthings.net/
which should be either http://redflare.ofthings.net/
or better https://github.com/stainsby/redflare

Btw., "a more modern competitor" sounds a bit harsh... 
What about "a modern, alternative implementation" or something along these lines?

**Comment by TheAssassin** [comment]
Since it is not just an alternative implementation (different features and look) I will probably just remove the word "more".
