### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by bonifarz** [TheAssassin/redflare-python#2]
Some of these FRs are trivial, some are kind of obvious.
Here's a list for you to keep track of things you could add:

* time left in minutes - *mm:ss* format would also be fine; maybe use ∞ for -1
* team colours on names - not so important, but could be nice to have
* stats: yes/no - this will be important for the upcoming release
* mode icons - this would be a big step forward, but since you have privs icons, i know you can do it
* mut icons - a bit more tedious, but this could be pretty cool; gspm should override mode icons
* map icons - probably not worth it, but still an option to consider
* country - we're used to that info from redflare, but it's not that important here

**Comment by TheAssassin** [comment]
I've created separate enhancement tasks to track the feature requests separately.
Please create separate issues for separate feature requests next time :)

**Comment by bonifarz** [comment]
Heh, whatever works best for you. I guess we don't need all child issues fixed in order to close this one.
