### ISSUE TITLE
Change player names' text colour to the team colour

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/redflare-python#4]
Another nice-to-have feature requested by @bonifarz in #2 is showing players' team's colour by changing their text colour to the team colour.

To accomplish this, a solution must be found to get the team name from query replies in the backend and then change the text colour in the frontend to this value.

**Comment by TheAssassin** [comment]
I have implemented the feature. It was rather easy since a player's team colour is sent in the query reply, too.

![example_with_colours](https://cloud.githubusercontent.com/assets/4503202/15949244/4bf626b2-2ea6-11e6-9575-3f00e7a8dfe4.png)

But I don't really like the look. Any Ideas?

**Comment by bonifarz** [comment]
I think "the look" is okay so far, except for the gray default of *teamneutralcolour*, which does not blend well with your background colors. Maybe you could check if the colour is 0x90A090 (default neutral) and replace that with black.
