### ISSUE TITLE
Display if the server supports stats

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/redflare-python#5]
@bonifarz requested displaying whether a server supports stats or not in #2.

I'm not sure what that feature is exactly. @bonifarz, a little more information is required.

**Comment by bonifarz** [comment]
Only some registered servers will track game statistics, as shown here: http://play.redeclipse.net:28700/

In the maps menu, the corresponding check is https://github.com/red-eclipse/base/blob/master/config/menus/servers.cfg#L79 or `(hasflag $sinfoflags s)` where `sinfoflags = (getserver $i 0 9)`. I don't know if you can get this flag easily in your query.

**Comment by shacknetisp** [comment]
The server's flags are sent as the second-to-last field returned by the Master Server:
_addserver 74.81.175.20 28803 4 "Master Server (play.redeclipse.net)" "redeclipse" **"sm"** "master"_
After that detecting statistics is as simple as testing if _s_ is in the flags field.

**Comment by TheAssassin** [comment]
Fixed in revisions 675a98e3 and 9dd5203d.
