### ISSUE TITLE
Display map preview pictures

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/redflare-python#8]
@bonifarz requested displaying map icons instead of or next to the maps in the frontend in #2. 

Similar to #6 and #7, I am not sure what these icons are and where to find those icons. Apart from that, just like @bonifarz I am not sure whether this is really useful and should be implemented. But let's first discuss it before rejecting the feature request.

**Comment by bonifarz** [comment]
There's no chance to work with SVGs here, these are the preview png images of the maps: https://github.com/red-eclipse/maps/find/master *.png
So, while this may look cool, it will be a pain to maintain, and also take quite some space, unless you use a script to scale them, e.g. from 512 to 64px

**Comment by TheAssassin** [comment]
I retitled the issue since it's about those preview pictures, and the word "icon" doesn't really fit. That's why I was a bit irritated when reading the feature request in #2 .

I don't really think it's worth including those pictures though. I already thought about displaying modal dialogs with extended information about servers, and such pictures would probably take up too much space without providing the user with important information.

If I should decide to implement it later, I will probably resize the pictures on demand and use a directory to cache the resized pictures. Then I can just include the base repository as a Git module.
